language: nix
env:
  - USE_CLANG=false USE_QT=false
  - USE_CLANG=false USE_QT=true
  - USE_CLANG=true USE_QT=false
  - USE_CLANG=true USE_QT=true
script:
  - nix-build --arg use_clang $USE_CLANG --arg use_qt $USE_QT
  - result/bin/01_linked_unit
