#########################
# project configuration #
#########################

# C++ project
language: cpp

# new modern dist, on docker
dist: trusty
sudo: false


# Is there any better way? Maybe yaml merge (<<) for compiler defs?
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env: COMPILER=g++-5
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.8
        packages:
          - clang-3.8
    env: COMPILER=clang++-3.8
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - ppa:beineri/opt-qt562-trusty
        packages:
          - g++-5
          - mesa-common-dev
          - qt56base
    env: 
      - COMPILER=g++-5
      - CMAKE_PREFIX_PATH=/opt/qt56
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.8
          - ppa:beineri/opt-qt562-trusty
        packages:
          - clang-3.8
          - mesa-common-dev
          - qt56base 
    env: 
      - COMPILER=clang++-3.8
      - CMAKE_PREFIX_PATH=/opt/qt56

addons:
  apt:
    packages:
    - cmake

script:
  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER  .
  - make all
  - ctest -V

