#########################
# project configuration #
#########################

# C++ project
language: cpp

# new modern dist, on docker
dist: trusty
sudo: false


# Is there any better way? Maybe yaml merge (<<) for compiler defs?
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env: COMPILER=g++-5
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
        packages:
          - clang-3.7
    env: COMPILER=clang++-3.7
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env: 
      - COMPILER=g++-5
      - CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Core/
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
        packages:
          - clang-3.7
    env: 
      - COMPILER=clang++-3.7
      - CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Core/

addons:
  apt:
    packages:
    - cmake
    - qtbase5-dev

script:
  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER  .
  - make all
  - make test

