#########################
# project configuration #
#########################

# C++ project
language: cpp

# new modern dist, on docker
dist: trusty
sudo: false


matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang

addons:
  apt:
    packages:
    - cmake
    - libqt5-dev

script:
  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - cmake .
  - make all
  - make test

