#########################
# project configuration #
#########################

# C++ project
language: cpp

# new modern dist, on docker
dist: trusty
sudo: false


matrix:
  include:
  - os: linux
    compiler: gcc
    env: 
      - _CC=gcc-4.9
      - _CXX=g++-4.9
  - os: linux
    compiler: clang
    env: 
      - _CC=clang
      - C_XX=clang++

addons:
  apt:
    packages:
    - cmake
    - qtbase5-dev
    - libc++-dev
    - gcc-4.9 

script:
  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - CC=$_CXX CXX=$_CXX cmake .
  - make all
  - make test

