language: nix
matrix:
  env:
  - USE_CLANG=false USE_QT=false
  - USE_CLANG=false USE_QT=true
  - USE_CLANG=true USE_QT=false
  - USE_CLANG=true USE_QT=true
script:
- nix-build --attr use_clang $USE_CLANG --attr use_qt $USE_QT
- result/bin/01_linked_unit
