language: nix
matrix:
  env:
  - USE_CLANG=false USE_QT=false
  - USE_CLANG=false USE_QT=true
  - USE_CLANG=true USE_QT=false
  - USE_CLANG=true USE_QT=true
script:
- nix-build --attr use_clang=$USE_CLANG --attr use_qt=$USE_QT
- result/bin/01_linked_unit

# #########################
# # project configuration #
# #########################

# # C++ project
# language: cpp

# # new modern dist, on docker
# dist: trusty
# sudo: false


# # Is there any better way? Maybe yaml merge (<<) for compiler defs?
# matrix:
#   include:
#   - os: linux
#     compiler: gcc
#     addons:
#       apt:
#         sources:
#           - ubuntu-toolchain-r-test
#         packages:
#           - g++-5
#     env: COMPILER=g++-5
#   - os: linux
#     compiler: clang
#     addons:
#       apt:
#         sources:
#           - ubuntu-toolchain-r-test
#           - llvm-toolchain-precise-3.7
#         packages:
#           - clang-3.7
#     env: COMPILER=clang++-3.7
#   - os: linux
#     compiler: gcc
#     addons:
#       apt:
#         sources:
#           - ubuntu-toolchain-r-test
#           - sourceline: deb http://ppa.launchpad.net/beineri/opt-qt562-trusty/ubuntu trusty main
#         packages:
#           - g++-5
#           - mesa-common-dev
#           - qt56base
#     env:
#       - COMPILER=g++-5
#       - CMAKE_PREFIX_PATH=/opt/qt56
#   - os: linux
#     compiler: clang
#     addons:
#       apt:
#         sources:
#           - ubuntu-toolchain-r-test
#           - llvm-toolchain-precise-3.7
#           - sourceline: deb http://ppa.launchpad.net/beineri/opt-qt562-trusty/ubuntu trusty main
#         packages:
#           - clang-3.7
#           - mesa-common-dev
#           - qt56base
#     env:
#       - COMPILER=clang++-3.7
#       - CMAKE_PREFIX_PATH=/opt/qt56

# addons:
#   apt:
#     packages:
#     - cmake

# script:
#   # show OS/compiler version
#   - uname -a
#   - $CXX --version

#   # compile and execute unit tests
#   - cmake -DCMAKE_CXX_COMPILER=$COMPILER  .
#   - make all
#   - ctest -V

